# This is a basic workflow to help you get started with Actions

name: CodeSync

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request_target:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Copybara Action 2"
        uses: olivr/copybara-action@v1.2.2
        with:
          sot_repo: wardsimon/bookish-computing-machine
          destination_repo: wardsimon/fictional-memory
          access_token: ${{ secrets.GH_TOKEN_BOT }}
          ssh_key: ${{ secrets.GH_SSH_BOT }}
          copybara_options: --force --init-history
